'use strict';

const { DataTypes } = require('sequelize');
const {
  STATUS,
  STATUS_VALUES,
  LEAD_STAGE,
  LEAD_STAGE_VALUES,
  DEVICE_TYPE,
  DEVICE_TYPE_VALUES,
} = require('../constants');

/**
 * One device that has visited a tenant's public website.
 *
 * This is the row the console's Lead Management table lists — **one per
 * device**, never one per visit. A person who comes back four times is one
 * lead with four visits, which is what a salesperson means by "a lead" and is
 * the whole reason this table exists separately from `lead_visits`: without it
 * the list would be a page-view log with a phone number column, and the same
 * person would appear four times over.
 *
 * `device_id` is the identity, generated by the website and kept in the
 * visitor's own browser storage. It is stable for that browser on that machine
 * and nothing more — a new browser, a cleared storage or a private window is a
 * new lead, honestly, rather than something guessed at by fingerprinting.
 *
 * Scoped to a company: the same visitor reading two tenants' websites is two
 * leads, because the two companies must never be able to see each other's
 * traffic. `(company_id, device_id)` is what every read matches on, and
 * `recordVisit` holds it unique with a find-then-create rather than a database
 * constraint — the same choice `company_functionalities` made, for the same
 * SQLite reason documented in `server.js`.
 *
 * ## First touch vs last touch
 *
 * Attribution is stored twice on purpose, because the two answer different
 * questions and a single copy silently answers neither:
 *
 *   `utmSource` / `utmMedium` / `utmCampaign` / … and the `first*` fields are
 *   **first touch** — the campaign that produced this lead. Written once, at
 *   creation, and never overwritten, so a lead that arrives from an ad and
 *   returns later by typing the address still counts for the ad.
 *
 *   The `last*` fields are **last touch** — where they came from most
 *   recently, which is what tells you a dormant lead has just clicked a new
 *   campaign.
 */
module.exports = (sequelize) =>
  sequelize.define(
    'Lead',
    {
      id: { type: DataTypes.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true },
      companyId: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
      /**
       * The branch whose domain this device first arrived on; NULL on a
       * company-wide host. Follows the same rule the rest of the schema uses,
       * and is what the super admin's branch-wise breakdown groups by.
       *
       * First arrival rather than latest: a lead belongs to the branch that won
       * it, and a visitor who later opens the company-wide site should not
       * quietly move between branch reports.
       */
      branchId: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },

      /** The browser-held identifier this lead *is*. See the class comment. */
      deviceId: { type: DataTypes.STRING(64), allowNull: false },

      stage: {
        type: DataTypes.ENUM(...LEAD_STAGE_VALUES),
        allowNull: false,
        defaultValue: LEAD_STAGE.NEW,
      },

      /**
       * Who they turned out to be.
       *
       * Empty for a lead that has only ever browsed — which is most of them —
       * and filled in when the same device submits something that names a
       * person, or when someone in the console types what they learned on the
       * phone. A visit never writes these.
       */
      name: { type: DataTypes.STRING(150), allowNull: true },
      email: { type: DataTypes.STRING(160), allowNull: true },
      phone: { type: DataTypes.STRING(20), allowNull: true },

      /**
       * The device's push token, as last reported.
       *
       * Latest-wins rather than a history: a token is a delivery address that
       * the platform rotates on its own, and an old one is not a fact about the
       * lead, it is an address that no longer works. Null is the normal case —
       * the website only has a token where the visitor granted notifications.
       */
      fcmToken: { type: DataTypes.STRING(512), allowNull: true },
      fcmUpdatedAt: { type: DataTypes.DATE, allowNull: true },

      /** How many visits are behind this lead — see `LEAD_VISIT_SESSION_MINUTES`. */
      visitCount: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
      /** Page loads, which is a larger number than visits and a different one. */
      pageViewCount: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
      firstSeenAt: { type: DataTypes.DATE, allowNull: true },
      lastSeenAt: { type: DataTypes.DATE, allowNull: true },

      /* ---------------- First touch: what produced this lead ---------------- */

      firstLandingUrl: { type: DataTypes.STRING(500), allowNull: true },
      firstReferrer: { type: DataTypes.STRING(500), allowNull: true },
      /** `www.google.com` — the host alone, which is what a report groups by. */
      firstReferrerHost: { type: DataTypes.STRING(180), allowNull: true },
      /** Every `utm_*` and click id the first URL carried, verbatim. */
      firstUtm: { type: DataTypes.JSON, allowNull: true },

      /**
       * The five campaign parameters, denormalised off `firstUtm` so the
       * console can filter and group on an index rather than reading JSON.
       * First touch — see the class comment.
       */
      utmSource: { type: DataTypes.STRING(160), allowNull: true },
      utmMedium: { type: DataTypes.STRING(160), allowNull: true },
      utmCampaign: { type: DataTypes.STRING(160), allowNull: true },
      utmTerm: { type: DataTypes.STRING(160), allowNull: true },
      utmContent: { type: DataTypes.STRING(160), allowNull: true },

      /* ---------------- Last touch: where they came from most recently ---------------- */

      lastLandingUrl: { type: DataTypes.STRING(500), allowNull: true },
      lastReferrer: { type: DataTypes.STRING(500), allowNull: true },
      lastReferrerHost: { type: DataTypes.STRING(180), allowNull: true },
      lastUtm: { type: DataTypes.JSON, allowNull: true },

      /* ---------------- The machine, as last seen ---------------- */

      deviceType: {
        type: DataTypes.ENUM(...DEVICE_TYPE_VALUES),
        allowNull: false,
        defaultValue: DEVICE_TYPE.UNKNOWN,
      },
      deviceVendor: { type: DataTypes.STRING(60), allowNull: true },
      deviceModel: { type: DataTypes.STRING(80), allowNull: true },
      os: { type: DataTypes.STRING(40), allowNull: true },
      osVersion: { type: DataTypes.STRING(40), allowNull: true },
      browser: { type: DataTypes.STRING(60), allowNull: true },
      browserVersion: { type: DataTypes.STRING(40), allowNull: true },

      /**
       * A crawler, a link previewer or an uptime check.
       *
       * Kept rather than dropped — a company whose lead count jumps overnight
       * deserves to see why — but flagged, so the counts the console leads with
       * exclude it and nobody rings a search engine.
       */
      isBot: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },

      /* ---------------- Where, as last seen ---------------- */

      ip: { type: DataTypes.STRING(45), allowNull: true },
      country: { type: DataTypes.STRING(80), allowNull: true },
      region: { type: DataTypes.STRING(80), allowNull: true },
      city: { type: DataTypes.STRING(80), allowNull: true },
      /** IANA name, e.g. `Asia/Kolkata`. The one location signal every browser gives. */
      timezone: { type: DataTypes.STRING(64), allowNull: true },
      /** Only ever set where the visitor granted the location permission. */
      latitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
      longitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
      language: { type: DataTypes.STRING(40), allowNull: true },

      /** What the company learned about them. The console's only free-text field. */
      notes: { type: DataTypes.TEXT, allowNull: true },

      status: { type: DataTypes.ENUM(...STATUS_VALUES), allowNull: false, defaultValue: STATUS.ACTIVE },
      updatedBy: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
    },
    {
      tableName: 'leads',
      indexes: [
        /**
         * The lookup every single tracking call makes. Not declared UNIQUE:
         * sequelize misreads a composite unique when it rebuilds a table on
         * SQLite — see the note in `server.js` — and `recordVisit` holds the
         * invariant in a transaction either way.
         */
        { fields: ['company_id', 'device_id'] },
        { fields: ['device_id'] },
        { fields: ['branch_id'] },
        { fields: ['stage'] },
        /** The list's default order, and what the analytics window filters on. */
        { fields: ['last_seen_at'] },
        { fields: ['created_at'] },
        { fields: ['utm_source'] },
        { fields: ['utm_campaign'] },
        { fields: ['device_type'] },
        { fields: ['is_bot'] },
        { fields: ['status'] },
      ],
    }
  );
