'use strict';

const { DataTypes } = require('sequelize');
const {
  STATUS,
  STATUS_VALUES,
  LEAD_STAGE,
  LEAD_STAGE_VALUES,
  DEVICE_TYPE,
  DEVICE_TYPE_VALUES,
} = require('../constants');

/**
 * One device that has visited **our own** marketing site.
 *
 * The same idea as `Lead` next door and deliberately the same column names, so
 * a report written against one reads against the other. The difference is the
 * whole reason this is a second table rather than a nullable column on the
 * first:
 *
 *   `leads` is **tenant data**. Every read of it is scoped to one company, and
 *   `company_id` being NOT NULL is what makes a missing scope a crash instead
 *   of a leak. Hanging our own traffic off that table would mean either a
 *   sentinel company id or a nullable scope column, and both turn that crash
 *   back into a silent cross-tenant read.
 *
 *   These rows belong to nobody but us. There is no company, no branch and
 *   nothing to scope by — which is exactly why they cannot live there.
 *
 * `device_id` is the identity, generated by the website and kept in the
 * visitor's own browser storage. Stable for that browser on that machine and
 * nothing more: a new browser, cleared storage or a private window is a new
 * lead, honestly, rather than something guessed at by fingerprinting.
 *
 * ## First touch vs last touch
 *
 * Stored twice on purpose, because the two answer different questions and one
 * copy silently answers neither:
 *
 *   `utmSource` / `utmMedium` / `utmCampaign` / … and the `first*` fields are
 *   **first touch** — the campaign that produced this lead. Written once, at
 *   creation, never overwritten, so somebody who arrives from an ad and comes
 *   back later by typing the address still counts for the ad.
 *
 *   The `last*` fields are **last touch** — where they came from most
 *   recently, which is what tells you a dormant lead has clicked a new
 *   campaign.
 */
module.exports = (sequelize) =>
  sequelize.define(
    'MarketingLead',
    {
      id: { type: DataTypes.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true },

      /** The browser-held identifier this lead *is*. See the note above. */
      deviceId: { type: DataTypes.STRING(64), allowNull: false },

      stage: {
        type: DataTypes.ENUM(...LEAD_STAGE_VALUES),
        allowNull: false,
        defaultValue: LEAD_STAGE.NEW,
      },

      /**
       * Who they turned out to be.
       *
       * Empty for a lead that has only ever browsed — which is most of them —
       * and filled in when the same device submits the demo or contact form,
       * or when somebody types what they learned on the phone. A visit never
       * writes these.
       */
      name: { type: DataTypes.STRING(150), allowNull: true },
      email: { type: DataTypes.STRING(160), allowNull: true },
      phone: { type: DataTypes.STRING(20), allowNull: true },

      /**
       * The enquiry this device sent, where it sent one.
       *
       * The join between "somebody browsed the pricing page four times" and
       * "somebody asked for a demo", which is the question the whole table
       * exists to answer. Null for the large majority who never write in.
       */
      enquiryId: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },

      /** How many visits are behind this lead — see `LEAD_VISIT_SESSION_MINUTES`. */
      visitCount: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
      /** Page loads, which is a larger number than visits and a different one. */
      pageViewCount: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
      firstSeenAt: { type: DataTypes.DATE, allowNull: true },
      lastSeenAt: { type: DataTypes.DATE, allowNull: true },

      /* ---------------- First touch: what produced this lead ---------------- */

      firstLandingUrl: { type: DataTypes.STRING(500), allowNull: true },
      firstReferrer: { type: DataTypes.STRING(500), allowNull: true },
      /** `www.google.com` — the host alone, which is what a report groups by. */
      firstReferrerHost: { type: DataTypes.STRING(180), allowNull: true },
      /** Every `utm_*` and click id the first URL carried, verbatim. */
      firstUtm: { type: DataTypes.JSON, allowNull: true },

      /**
       * The five campaign parameters, denormalised off `firstUtm` so the
       * console filters and groups on an index rather than reading JSON.
       * First touch — see the note above.
       */
      utmSource: { type: DataTypes.STRING(160), allowNull: true },
      utmMedium: { type: DataTypes.STRING(160), allowNull: true },
      utmCampaign: { type: DataTypes.STRING(160), allowNull: true },
      utmTerm: { type: DataTypes.STRING(160), allowNull: true },
      utmContent: { type: DataTypes.STRING(160), allowNull: true },

      /* ------------- Last touch: where they came from most recently ------------- */

      lastLandingUrl: { type: DataTypes.STRING(500), allowNull: true },
      lastReferrer: { type: DataTypes.STRING(500), allowNull: true },
      lastReferrerHost: { type: DataTypes.STRING(180), allowNull: true },
      lastUtm: { type: DataTypes.JSON, allowNull: true },

      /* ---------------- The machine, as last seen ---------------- */

      deviceType: {
        type: DataTypes.ENUM(...DEVICE_TYPE_VALUES),
        allowNull: false,
        defaultValue: DEVICE_TYPE.UNKNOWN,
      },
      deviceVendor: { type: DataTypes.STRING(60), allowNull: true },
      deviceModel: { type: DataTypes.STRING(80), allowNull: true },
      os: { type: DataTypes.STRING(40), allowNull: true },
      osVersion: { type: DataTypes.STRING(40), allowNull: true },
      browser: { type: DataTypes.STRING(60), allowNull: true },
      browserVersion: { type: DataTypes.STRING(40), allowNull: true },

      /**
       * A crawler, a link previewer or an uptime check.
       *
       * Kept rather than dropped — traffic that jumps overnight deserves to
       * show why — but flagged, so the counts the console leads with exclude it
       * and nobody rings a search engine.
       */
      isBot: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },

      /* ---------------- Where, as last seen ---------------- */

      ip: { type: DataTypes.STRING(45), allowNull: true },
      country: { type: DataTypes.STRING(80), allowNull: true },
      region: { type: DataTypes.STRING(80), allowNull: true },
      city: { type: DataTypes.STRING(80), allowNull: true },
      /** IANA name, e.g. `Asia/Kolkata`. The one location signal every browser gives. */
      timezone: { type: DataTypes.STRING(64), allowNull: true },
      /** Only ever set where the visitor granted the location permission. */
      latitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
      longitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
      language: { type: DataTypes.STRING(40), allowNull: true },

      /** What we learned about them. The console's only free-text field. */
      notes: { type: DataTypes.TEXT, allowNull: true },

      status: { type: DataTypes.ENUM(...STATUS_VALUES), allowNull: false, defaultValue: STATUS.ACTIVE },
      updatedBy: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
    },
    {
      tableName: 'marketing_leads',
      indexes: [
        /**
         * The lookup every tracking call makes. Not declared UNIQUE:
         * sequelize misreads a unique index when it rebuilds a table on
         * SQLite — see the note in `server.js` — and `recordVisit` holds the
         * invariant with a locked find-or-create either way.
         */
        { fields: ['device_id'] },
        { fields: ['stage'] },
        /** The list's default order, and what the analytics window filters on. */
        { fields: ['last_seen_at'] },
        { fields: ['created_at'] },
        { fields: ['utm_source'] },
        { fields: ['utm_campaign'] },
        { fields: ['device_type'] },
        { fields: ['is_bot'] },
        { fields: ['status'] },
      ],
    }
  );
